[package]
name = "project-starforged"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
path = "shared/lib.rs"

[[bin]]
name = "server"
path = "server/lib.rs"

[[bin]]
name = "client"
path = "client/lib.rs"

[dependencies]
bytemuck = "1.18.0"
cached = "0.53.1"
nalgebra = "0.33.0"
noise = "0.9.0"
once_cell = "1.20.2"
splines = "4.3.1"
stopwatch = "0.0.7"
wgpu = "22.1.0"
